version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db:/data/db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=devpg
    ports:
      - '5432:5432'
  web:
    image: node:16
    build:
      context: .
    restart: always
    volumes:
      - .:/usr/app
    ports:
      - "4003:4003"
    environment:
      - MONGO_URL=mongodb://mongo:27017/purchase-list
    stdin_open: true
    tty: true
    depends_on:
      - db

volumes:
  db: